name: Django CI

on:[push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Run Tests
      env:
        AMADEUS_API_SECRET_KEY: ${{ secrets.AMADEUS_API_SECRET_KEY }}
        AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
        GEODB_X_RAPID_API_KEY: ${{ secrets.GEODB_X_RAPID_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
        WEATHER_BIT_X_RAPID_API_KEY: ${{ secrets.WEATHER_BIT_X_RAPID_API_KEY }}
        FOURSQUARE_API_KEY: ${{ secrets.FOURSQUARE_API_KEY }}
      run: |
        python manage.py test
        coverage run --source=info,search --omit=*/migrations/* ./manage.py test
        coverage report
        coverage html
        
    - name: Upload cov
      uses: codecov/codecov-action@v2
      with:
        token: 3ad2c88d-e733-429b-962e-bc9db2760b01
    - name: lint with flake
      run: flake8 --ignore=E501
